import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ThemeProvider, createTheme, makeStyles } from '@mui/material/styles';
import HomePage from './HomePage'

const theme = createTheme({
  palette: {
    primary: {
      main: '#fff'
    },
    secondary: {
      main: '#424242'
    },
    lightGray: {
      main: '#bdbdbd'
    },
    red: {
      main: '#f44336'
    }
  },
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>

        <HomePage/>
      </ThemeProvider>
    </div>
  );
}
